### PR TITLE
New homepage

### PR DESCRIPTION
**Pull request by bhuffy**
What's in pull request:
- Contains draft of new homepage with 15 images
- No scroll effect, but css animated images
- Cleaned up CSS files for index page
- Initial darkmode conversion (other page layouts slightly broken at the moment)
- Universal grid system (`grid.css`)
- Universal nav (`nav.css`)
- Archive files removed

Todo (diff branch)
- Many unused images and files still in `assets` and `main-content` folders. Should delete in dev branch

### CODE REVIEW

**Comment by mikinty** [comment]
Do you have screenshots or a video showing what the new site looks like?

**Comment by josephz-me** [comment]
> Do you have screenshots or a video showing what the new site looks like?

Mockups:
Screen Shot 2021-11-03 at 12 17 05 AM

**Review by mikinty — APPROVED** [review]
Looks fine to me.

Honestly given the size of this repo I'd recommend starting a new repo if possible. Also using a newer web framework like React would be great...but I know y'all don't have time in school :(

**Comment by bhuffy** [comment]
> Looks fine to me.
> 
> Honestly given the size of this repo I'd recommend starting a new repo if possible. Also using a newer web framework like React would be great...but I know y'all don't have time in school :(

Yeah we'll be splitting up all the projects/websites in to their own repos and cleaning it up before merging the dev branch back into main. We have to start working on the event website already, so probably no frameworks for this release!

**Pull request merged**
